version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to docker registry...
      - docker login -u rragavendira -p ragav123
       
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t rragavendira:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push rragavendira:latest
  
      
